GG-2187 more optimizations
one-up-games/DotRecast pull request #2
Opened 2024-08-20 17:02 UTC by NikolayGrigoryev

2024-08-20 17:11 UTC, nikita-one commented on src/DotRecast.Detour/DtNodeSortedQueue.cs
> +            _items.Add(item.total, item);
Там total точно не меняется по коду потом по рефу? А то не понятно, какие юзинги там у DtNode снаружи

2024-08-20 17:12 UTC, nikita-one commented on src/DotRecast.Detour/DtNodeSortedQueue.cs
> +            for (int i = 0; i < values.Count; i++)
В целом может можно тут бинарный поиск сделать, если каунт больше 20 условно.

2024-08-20 17:12 UTC, nikita-one approved these changes

2024-08-20 17:30 UTC, NikolayGrigoryev commented on src/DotRecast.Detour/DtNodeSortedQueue.cs
> +            for (int i = 0; i < values.Count; i++)
А тут они по ссылке сравниваются. Если только самим посмотреть по ключу тоталу бинарно.

2024-08-20 19:24 UTC, nikita-one commented on src/DotRecast.Detour/DtNodeSortedQueue.cs
> +            for (int i = 0; i < values.Count; i++)
Ну да, рукми прям бинарный поиск написать (списать)

2024-08-21 13:48 UTC, NikolayGrigoryev commented on src/DotRecast.Detour/DtNodeSortedQueue.cs
> +            _items.Add(item.total, item);
Меняется, и постоянно, и по этому же и бинари серч не всегда возможен(

2024-08-21 13:48 UTC, NikolayGrigoryev commented on src/DotRecast.Detour/DtNodeSortedQueue.cs
> +            _items.Add(item.total, item);
Переписал еще раз в другом русле

2024-08-21 13:50 UTC, NikolayGrigoryev commented on src/DotRecast.Detour/DtNodeSortedQueue.cs
> +            for (int i = 0; i < values.Count; i++)
бинарисерч отвалился, тк в момент вставки уже сортировка значений разрушена по ссылке обьектов.

2024-08-22 13:13 UTC, nikita-one commented on src/DotRecast.Detour/DtNavMeshQuery.cs
> +            for (var i = 0; i < _polys.Length; i++)
Длину лучше в локальную переменную сохранить, чуть чуть побыстрее будет

2024-08-22 13:13 UTC, nikita-one commented on src/DotRecast.Detour/DtNavMeshQuery.cs
> +            for (var i = 0; i < _polys.Length; i++)
А ну в данном случае можно BatchSize заюзать, если уже есть константа

2024-08-22 13:17 UTC, nikita-one commented on src/DotRecast.Detour/DtNodeSortedQueue.cs
> +    public class DtNodeSortedQueue
Юнит тест нужен. Там наверняка есть тест для исходной очереди какой-то, нужно хотя бы его скопипастить, и проверить что для этой реализации он тоже проходит

2024-08-22 14:34 UTC, nikita-one commented on src/DotRecast.Detour/DtNodeSortedQueue.cs
> +            _comparer = Comparer<DtNode>.Create(Comparer);
Я дабл чекнул у себя, проблема сугубо в этом коде. Аллочит компарер. Если заменить его на Comparison (делегат), то аллокаций нет в List.Sort, и работает ощутимо быстре за счет дженериков.

2024-08-22 14:35 UTC, nikita-one commented on src/DotRecast.Detour/DtNodeSortedQueue.cs
> +            _comparer = Comparer<DtNode>.Create(Comparer);
Мне кажется это можно исправить прям в исходной очереди, тогда не надо отдельный тест писать, и возможно там для других юзингов тоже поможет, если она используется там где-то. Тут вроде не деструктивные изменения

2024-08-22 14:36 UTC, nikita-one requested changes
Отписался выше. Нужно заюзать List.Sort с делегатом

2024-08-22 15:19 UTC, nikita-one commented on src/DotRecast.Core/Collections/RcSortedQueue.cs
> -            _comparer = Comparer<T>.Create((x, y) => comp.Invoke(x, y) * -1);
тут должна лябда остаться мне кажется. Типа 
_comp = (x, y) => comp.Invoke(x, y) * -1;

2024-08-22 15:19 UTC, nikita-one commented on src/DotRecast.Core/Collections/RcSortedQueue.cs
> -            _comparer = Comparer<T>.Create((x, y) => comp.Invoke(x, y) * -1);
Там вероятно есть другию юзинги у этой очереди, иначе они сломаются

2024-08-22 15:20 UTC, nikita-one commented on src/DotRecast.Detour/DtNodeQueue.cs
> +            m_heap = new RcSortedQueue<DtNode>(_comparer);
Наверно нужно оставить тут все как было.

2024-08-22 15:41 UTC, nikita-one commented on src/DotRecast.Core/Collections/RcSortedQueue.cs
>              int idx = _items.FindLastIndex(x => item.Equals(x));
Тут был хороший чендж у тебя, с тем чтобы for тут был вместо замыкания. Мне кажется можно его воскресить, чтобы не аллочило.

2024-08-22 15:51 UTC, nikita-one approved these changes
Про удаление еще добавил коммент, а так норм

2026-06-12 14:01 UTC, closed without merging